server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/venus_commerce?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
#    password: ${MYSQL_PASSWORD}
#    username: ${MYSQL_USER}
    hikari:
#      连接池名称
      pool-name: VenusHikariGP
#      连接池中最小连接数量
      minimum-idle: 5
#      最大连接数量
      maximum-pool-size: 20
#      连接超时
      connection-timeout: 3000
#      连接池中超时连接回收时间
      idle-timeout: 600000
#      最大连接存活时间
      max-lifetime: 1800000
  config:
    import: "optional:classpath:application-local.yml"
  servlet:
    multipart:
      enabled: true
        # 单个文件最大 10MB
      max-file-size: 10MB
        # 请求总大小最大 100MB
      max-request-size: 100MB
logging:
    level:
        # 将这两个都设为 TRACE
      org.springframework.security: TRACE
      org.springframework.web: TRACE